(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Program: ErrorHandling
 * File: errorHandlingInit.st
 * Author: Bernecker + Rainer
 * Created: March 01, 2011
 ********************************************************************
  * Implementation OF PROGRAM ErrorHandling
 ********************************************************************)

PROGRAM _INIT
    AcknowledgeStep := STATE_ERROR_SCAN;
END_PROGRAM